name: Build images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      run: |
        curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
        . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

    - name: debug
      run: |
        ls -la /boot/

    - name: Build images
      run: |
        nix-env -i nixos-generators qemu -f '<nixpkgs>'
        sudo .github/workflows/build.sh

    - name: Upload artifacts
      run: |
        ls -l result*/